export const BoardsServiceKeys = {
    BOARDS_SERVICE_GRPC_URL: "BOARDS_GRPC_URL",

    BOARD_NODES_SERVICE_GRPC_URL: "BOARD_NODES_GRPC_URL",

    // Postgres
    BOARDS_SERVICE_SQL_DB_NAME: "SQL_DB_NAME",
    BOARDS_SERVICE_SQL_DB_HOST: "SQL_DB_HOST",
    BOARDS_SERVICE_SQL_DB_PORT: "SQL_DB_PORT",
    BOARDS_SERVICE_SQL_DB_USER: "SQL_DB_USER",
    BOARDS_SERVICE_SQL_DB_PASS: "SQL_DB_PASS",

    // MongoDB
    BOARDS_SERVICE_NOSQL_DB_NAME: "NOSQL_DB_NAME",
    BOARDS_SERVICE_NOSQL_DB_HOST: "NOSQL_DB_HOST",
    BOARDS_SERVICE_NOSQL_DB_PORT: "NOSQL_DB_PORT",

    // Redis
    BOARDS_SERVICE_REDIS_HOST: "REDIS_HOST",
    BOARDS_SERVICE_REDIS_PORT: "REDIS_PORT",
    BOARDS_SERVICE_REDIS_DEFAULT_TTL: "REDIS_DEFAULT_TTL",

    // RabbitMQ
    BOARDS_SERVICE_RMQ_QUEUE: "RMQ_QUEUE",

    // RabbitMQ
    RMQ_URLS: "RMQ_URLS"
};
