export const GatewayKeys = {
    GATEWAY_SERVICE_APP_PORT: "APP_PORT",

    // JWT
    JWT_SECRET: "JWT_SECRET",
    ACCESS_JWT_EXPIRATION: "ACCESS_JWT_EXPIRATION",
    REFRESH_JWT_EXPIRATION: "REFRESH_JWT_EXPIRATION",

    // Cookie
    COOKIE_HTTP_ONLY: "COOKIE_HTTP_ONLY",
    COOKIE_SECURE: "COOKIE_SECURE",
    COOKIE_SAME_SITE: "COOKIE_SAME_SITE",
    ACCESS_COOKIE_EXPIRATION: "ACCESS_COOKIE_EXPIRATION",
    REFRESH_COOKIE_EXPIRATION: "REFRESH_COOKIE_EXPIRATION",

    // Swagger
    SWAGGER_PATH: "SWAGGER_PATH",
    SWAGGER_TITLE: "SWAGGER_TITLE",
    SWAGGER_DESCRIPTION: "SWAGGER_DESCRIPTION",
    SWAGGER_VERSION: "SWAGGER_VERSION",
    SWAGGER_TAGS: "SWAGGER_TAGS",

    // Postgres
    GATEWAY_SERVICE_SQL_DB_NAME: "SQL_DB_NAME",
    GATEWAY_SERVICE_SQL_DB_HOST: "SQL_DB_HOST",
    GATEWAY_SERVICE_SQL_DB_PORT: "SQL_DB_PORT",
    GATEWAY_SERVICE_SQL_DB_USER: "SQL_DB_USER",
    GATEWAY_SERVICE_SQL_DB_PASS: "SQL_DB_PASS",

    // Boards Service
    BOARDS_SERVICE_GRPC_URL: "BOARDS_SERVICE_GRPC_URL",
    BOARD_NODES_SERVICE_GRPC_URL: "BOARD_NODES_SERVICE_GRPC_URL",
    BOARDS_SERVICE_RMQ_QUEUE: "BOARDS_SERVICE_RMQ_QUEUE",

    // Media Service
    MEDIA_SERVICE_GRPC_URL: "MEDIA_SERVICE_GRPC_URL",

    // RabbitMQ
    RMQ_URLS: "RMQ_URLS",

    // Web
    WEB_URL: "FRONTEND_URL"
};
