export const MediaServiceKeys = {
    MEDIA_SERVICE_GRPC_URL: "MEDIA_GRPC_URL",

    // Assets
    ASSETS_DIRECTORY: "ASSETS_DIRECTORY",

    // Postgres
    MEDIA_SERVICE_SQL_DB_NAME: "SQL_DB_NAME",
    MEDIA_SERVICE_SQL_DB_HOST: "SQL_DB_HOST",
    MEDIA_SERVICE_SQL_DB_PORT: "SQL_DB_PORT",
    MEDIA_SERVICE_SQL_DB_USER: "SQL_DB_USER",
    MEDIA_SERVICE_SQL_DB_PASS: "SQL_DB_PASS",

    // Redis
    MEDIA_SERVICE_REDIS_HOST: "REDIS_HOST",
    MEDIA_SERVICE_REDIS_PORT: "REDIS_PORT",
    MEDIA_SERVICE_REDIS_DEFAULT_TTL: "REDIS_DEFAULT_TTL",

    // S3
    S3_REGION: "S3_REGION",
    S3_ENDPOINT: "S3_ENDPOINT",
    S3_BUCKET: "S3_BUCKET",
    S3_ACCESS_KEY: "S3_ACCESS_KEY",
    S3_SECRET_KEY: "S3_SECRETE_KEY",
    S3_URL_EXPIRATION: "S3_URL_EXPIRATION"
};
