services:
    gateway:
        container_name: gateway
        depends_on:
            - gateway-slq-db
        build:
            context: .. 
            dockerfile: apps/gateway/Dockerfile
            args:
                APP_PORT: ${GATEWAY_SERVICE_APP_PORT}
        env_file:
            - ../apps/gateway/.env
        ports:
            - ${GATEWAY_SERVICE_APP_PORT}:${GATEWAY_SERVICE_APP_PORT}
        restart: unless-stopped

    gateway-slq-db:
        container_name: gateway-slq-db
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_DB=${GATEWAY_SERVICE_SQL_DB_NAME}
            - POSTGRES_USER=${GATEWAY_SERVICE_SQL_DB_USER}
            - POSTGRES_PASSWORD=${GATEWAY_SERVICE_SQL_DB_PASS}
        ports:
            - ${GATEWAY_SERVICE_SQL_DB_MANAGEMENT_PORT}:5432
        volumes:
            - gateway-postgres_data:/var/lib/postgresql/data



    boards-service:
        container_name: boards-service
        depends_on:
            - boards-slq-db
            - boards-nosql-db
            # - rabbitmq
        build:
            context: ..
            dockerfile: apps/boards/Dockerfile
        env_file:
            - ../apps/boards/.env
        restart: unless-stopped
        
    boards-slq-db:
        container_name: boards-slq-db 
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_DB=${BOARDS_SERVICE_SQL_DB_NAME}
            - POSTGRES_USER=${BOARDS_SERVICE_SQL_DB_USER}
            - POSTGRES_PASSWORD=${BOARDS_SERVICE_SQL_DB_PASS}
        ports:
            - ${BOARDS_SERVICE_SQL_DB_MANAGEMENT_PORT}:5432
        volumes:
            - boards-postgres_data:/var/lib/postgresql/data
  
    boards-nosql-db:
        container_name: boards-nosql-db
        image: mongo:latest
        environment:
            - MONGO_INITDB_DATABASE=${BOARDS_SERVICE_NOSQL_DB_NAME}
        ports:
            - ${BOARDS_SERVICE_NOSQL_DB_MANAGEMENT_PORT}:27017
    


    # media-service:
    #     container_name: media-service
    #     depends_on:
    #         - media-slq-db
    #         - minio
    #     build:
    #         context: ..
    #         dockerfile: apps/media/Dockerfile
    #     env_file:
    #         - ../apps/media/.env
    #     restart: unless-stopped

    # media-slq-db:
    #     container_name: media-slq-db
    #     image: postgres:15.2
    #     restart: always
    #     environment:
    #         - POSTGRES_DB=${MEDIA_SERVICE_SQL_DB_NAME}
    #         - POSTGRES_USER=${MEDIA_SERVICE_SQL_DB_USER}
    #         - POSTGRES_PASSWORD=${MEDIA_SERVICE_SQL_DB_PASS}
    #     ports:
    #         - ${MEDIA_SERVICE_SQL_DB_MANAGEMENT_PORT}:5432
    #     volumes:
    #         - media-postgres_data:/var/lib/postgresql/data
    



    # rabbitmq:
    #     image: rabbitmq:3-management
    #     container_name: rabbitmq
    #     ports:
    #         - ${RMQ_PORT}:5672
    #         - ${RMQ_MANAGEMENT_PORT}:15672

    # minio:
    #     image: quay.io/minio/minio:latest
    #     container_name: minio
    #     ports:
    #         - ${S3_PORT}:9000
    #         - ${S3_UI_PORT}:9001
    #     environment:
    #         MINIO_ROOT_USER: ${S3_USER}
    #         MINIO_ROOT_PASSWORD: ${S3_PASS}
    #     volumes:
    #         - ../data/minio:/data
    #     command: server /data --console-address ":9001"
    #     healthcheck:
    #         test: ["CMD", "mc", "ready", "local"]
    #         interval: 5s
    #         timeout: 5s
    #         retries: 5

volumes:
    gateway-postgres_data:
    boards-postgres_data: 
    # media-postgres_data:  

