services:
    gateway-slq-db:
        container_name: gateway-slq-db
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_DB=${GATEWAY_SERVICE_SQL_DB_NAME}
            - POSTGRES_USER=${GATEWAY_SERVICE_SQL_DB_USER}
            - POSTGRES_PASSWORD=${GATEWAY_SERVICE_SQL_DB_PASS}
        ports:
            - ${GATEWAY_SERVICE_SQL_DB_PORT}:5432
        volumes:
            - gateway-sql-db-data:/var/lib/postgresql/data

volumes:
    gateway-sql-db-data:
