services:
    supabase-db:
        image: supabase/postgres:15.1.1.78
        container_name: supabase-db
        environment:
            POSTGRES_PASSWORD: ${SUPABASE_DB_PASS}
            POSTGRES_DB: ${SUPABASE_DB_NAME}
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    supabase-auth:
        image: supabase/gotrue:v2.132.3
        container_name: supabase-auth
        depends_on:
            supabase-db:
                condition: service_healthy
        ports:
            - ${GOTRUE_PORT}:9999
        environment:
            GOTRUE_DB_DRIVER: postgres
            DATABASE_URL: postgres://${SUPABASE_DB_USER}:${SUPABASE_DB_PASS}@supabase-db:5432/${SUPABASE_DB_NAME}?sslmode=disable
            GOTRUE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
            GOTRUE_JWT_EXP: ${SUPABASE_JWT_EXPIRATION}
            GOTRUE_MAILER_AUTOCONFIRM: "true"
            GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
            GOTRUE_SITE_URL: ${WEB_URL}
            API_EXTERNAL_URL: ${GATEWAY_SERVICE_APP_URL}

    gateway:
        container_name: gateway
        image: calypso/gateway:latest
        build:
            context: ..
            dockerfile: apps/gateway/Dockerfile
            args:
                APP_PORT: ${GATEWAY_SERVICE_APP_PORT}
        env_file:
            - ../apps/gateway/.env
        ports:
            - ${GATEWAY_SERVICE_APP_PORT}:${GATEWAY_SERVICE_APP_PORT}
        restart: unless-stopped
        depends_on:
            supabase-auth:
                condition: service_started
