services:
    gateway:
        container_name: gateway
        image: calypso/gateway:latest
        depends_on:
            - gateway-slq-db
        build:
            context: ..
            dockerfile: apps/gateway/Dockerfile
            args:
                APP_PORT: ${GATEWAY_SERVICE_APP_PORT}
        env_file:
            - ../apps/gateway/.env
        ports:
            - ${GATEWAY_SERVICE_APP_PORT}:${GATEWAY_SERVICE_APP_PORT}
        restart: unless-stopped

    gateway-slq-db:
        container_name: gateway-slq-db
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_DB=${GATEWAY_SERVICE_SQL_DB_NAME}
            - POSTGRES_USER=${GATEWAY_SERVICE_SQL_DB_USER}
            - POSTGRES_PASSWORD=${GATEWAY_SERVICE_SQL_DB_PASS}
        ports:
            - ${GATEWAY_SERVICE_SQL_DB_PORT}:5432
        volumes:
            - gateway-postgres_data:/var/lib/postgresql/data

volumes:
    gateway-postgres_data: