name: CI

on:
    push:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup

            - name: Format
              run: bun format:check

            - name: Lint
              run: bun lint:check

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup

            - name: Build
              run: bun run build

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup

            - name: Unit tests
              run: bun run test:unit
