name: Code Analysis

on:
  schedule:
    - cron: '0 17 * * 4'
  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Type check
        run: bun run type-check
    
  knip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Unused code analysis
        run: bun run knip
